version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      client-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(client)"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      server-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(server)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
